import http from "k6/http";

const SEARCH_ENDPOINT = "https://api2.cf-northwind.com";

export default function () {
  http.get(
    SEARCH_ENDPOINT + "/api/search?table=products&q=" + getRandomSearchTerm()
  );
}

export const options = {
  scenarios: {
    ramping_load: {
      executor: "ramping-arrival-rate",
      preAllocatedVUs: 300,

      stages: [
        // Ramp up to 1,000 / sec in the first 30 seconds
        { target: 1000, duration: "30s" },

        // Then ramp up to 11,000 / sec over the next minute
        { target: 11000, duration: "1m" },

        // And hold for 30 seconds
        { target: 11000, duration: "30s" },
      ],
    },
  },
  cloud: {
    // Distribute between 8 locations globally
    distribution: {
      usEast1: { loadZone: "amazon:us:ashburn", percent: 15 },
      usEast2: { loadZone: "amazon:us:columbus", percent: 15 },
      usWest1: { loadZone: "amazon:us:palo alto", percent: 15 },
      usWest2: { loadZone: "amazon:us:portland", percent: 15 },
      eu1: { loadZone: "amazon:de:frankfurt", percent: 10 },
      eu2: { loadZone: "amazon:ie:dublin", percent: 10 },
      eu3: { loadZone: "amazon:gb:london", percent: 10 },
      eu4: { loadZone: "amazon:fr:paris", percent: 10 },
    },
  },
};

function getRandomSearchTerm() {
  const searchTerms = [
    "chai",
    "chang",
    "aniseed",
    "syrup",
    "chef",
    "anton",
    "cajun",
    "seasoning",
    "chef",
    "anton",
    "gumbo",
    "mix",
    "grandma",
    "boysenberry",
    "spread",
    "uncle",
    "bob",
    "organic",
    "dried",
    "pear",
    "northwood",
    "cranberry",
    "sauce",
    "mishi",
    "kobe",
    "niku",
    "ikura",
    "queso",
    "cabrale",
    "queso",
    "manchego",
    "la",
    "pastora",
    "konbu",
    "tofu",
    "genen",
    "shouyu",
    "pavlova",
    "alice",
    "mutton",
    "carnarvon",
    "tiger",
    "teatime",
    "chocolate",
    "biscuit",
    "sir",
    "rodney",
    "marmalade",
    "sir",
    "rodney",
    "scone",
    "gustaf",
    "tunnbrod",
    "guarana",
    "fantastica",
    "nunuca",
    "nougat",
    "creme",
    "gumbar",
    "gummibarchen",
    "schoggi",
    "schokolade",
    "rossle",
    "sauerkraut",
    "thuringer",
    "rostbratwurst",
    "nord",
    "ost",
    "matjeshering",
    "gorgonzola",
    "telino",
    "mascarpone",
    "fabioli",
    "geitost",
    "sasquatch",
    "ale",
    "steeleye",
    "stout",
    "inlagd",
    "sill",
    "gravad",
    "lax",
    "cote",
    "de",
    "blaye",
    "chartreuse",
    "verte",
    "boston",
    "crab",
    "meat",
    "jack",
    "new",
    "england",
    "clam",
    "chowder",
    "singaporean",
    "hokkien",
    "fried",
    "mee",
    "ipoh",
    "coffee",
    "gula",
    "malacca",
    "rogede",
    "sild",
    "spegesild",
    "zaanse",
    "koeken",
    "chocolade",
    "maxilaku",
    "valkoinen",
    "suklaa",
    "manjimup",
    "dried",
    "apple",
    "filo",
    "mix",
    "perth",
    "pasty",
    "tourtiere",
    "chinois",
    "gnocchi",
    "di",
    "nonna",
    "alice",
    "ravioli",
    "angelo",
    "escargot",
    "de",
    "bourgogne",
    "raclette",
    "courdavault",
    "camembert",
    "pierrot",
    "sirop",
    "derable",
    "tarte",
    "au",
    "sucre",
    "vegie",
    "spread",
    "wimmer",
    "gute",
    "semmelknodel",
    "louisiana",
    "fiery",
    "hot",
    "pepper",
    "sauce",
    "louisiana",
    "hot",
    "spiced",
    "okra",
    "laughing",
    "lumberjack",
    "lager",
    "scottish",
    "longbread",
    "gudbrandsdalsost",
    "outback",
    "lager",
    "flotemysost",
    "mozzarella",
    "di",
    "giovanni",
    "rod",
    "kaviar",
    "longlife",
    "tofu",
    "rhonbrau",
    "klosterbier",
    "lakkalikori",
    "original",
    "frankfurter",
    "grune",
    "sosse",
  ];
  return searchTerms[Math.floor(Math.random() * searchTerms.length)];
}
